# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'NotificationContentExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NotificationContentExtension

end

target 'NotificationService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NotificationService

end

target 'Urgence' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Urgence
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Functions'
  pod 'Firebase/Messaging'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'IQKeyboardManagerSwift'
end
